Table gender {
  genderId int [pk]
  name text
  createdAt datetime
  updatedAt datetime
}

Table roles {
  roleId int [pk]
  name text
  createdAt datetime
  updatedAt datetime
}

Table units {
  unitId int [pk]
  name text
  abbreviation text
  createdAt datetime
  updatedAt datetime
}

Table users {
  userId int [pk]
  genderId int
  roleId int
  firstName text
  lastName text
  username varchar(255) [unique]
  email varchar(255) [unique]
  password text
  avatarUrl text
  bio text
  createdAt datetime
  updatedAt datetime
}

Table ingredients {
  ingredientId int [pk]
  unitId int
  name text
  createdAt datetime
  updatedAt datetime
}

Table recipes {
  recipeId int [pk]
  userId int
  name text
  description text
  viewCount int
  likeCount int
  dislikeCount int
  thumbnailUrl text
  linkedCourseId int
  createdAt datetime
  updatedAt datetime
}

Table recipe_comments {
  recipeCommentId int [pk]
  userId int
  comment text
  createdAt datetime
  updatedAt datetime
}

Table courses {
  courseId int [pk]
  videoUrl text
  userId int
  thumbnailUrl text
  name text
  viewCount int
  rating decimal
  linkedRecipeId int
  description text
  createdAt datetime
  updatedAt datetime
}

Table course_comments {
  courseCommentId int [pk]
  userId int
  comment text
  createdAt datetime
  updatedAt datetime
}

Table reaction_types {
  reactionTypeId int [pk]
  name text
  createdAt datetime
  updatedAt datetime
}

Table course_ingredients {
  ingredientId int [pk]
  courseId int [pk]
  amount decimal
  createdAt datetime
  updatedAt datetime
}

Table recipe_ingredients {
  ingredientId int [pk]
  recipeId int [pk]
  amount decimal
  createdAt datetime
  updatedAt datetime
}

Table recipe_reactions {
  reactionTypeId int [pk]
  recipeId int [pk]
  userId int [pk]
  createdAt datetime
  updatedAt datetime
}

Table course_ratings {
  courseId int [pk]
  userId int [pk]
  rating decimal
  createdAt datetime
  updatedAt datetime
}

Table payments {
  paymentId int [pk]
  courseId int
  userId int
  amount decimal
  createdAt datetime
  updatedAt datetime
}

Table recipe_steps {
  recipeStepId int [pk]
  recipeId int
  stepNumber int
  description text
  createdAt datetime
  updatedAt datetime
}

Table course_steps {
  courseStepId int [pk]
  courseId int
  stepNumber int
  description text
  createdAt datetime
  updatedAt datetime
}

Ref: users.genderId > gender.genderId
Ref: users.roleId > roles.roleId

Ref: ingredients.unitId > units.unitId
Ref: recipes.userId > users.userId
Ref: courses.userId > users.userId

Ref: recipe_comments.userId > users.userId
Ref: course_comments.userId > users.userId

Ref: course_ingredients.ingredientId > ingredients.ingredientId
Ref: course_ingredients.courseId > courses.courseId

Ref: recipe_ingredients.ingredientId > ingredients.ingredientId
Ref: recipe_ingredients.recipeId > recipes.recipeId

Ref: recipe_reactions.reactionTypeId > reaction_types.reactionTypeId
Ref: recipe_reactions.recipeId > recipes.recipeId
Ref: recipe_reactions.userId > users.userId

Ref: course_ratings.courseId > courses.courseId
Ref: course_ratings.userId > users.userId

Ref: payments.courseId > courses.courseId
Ref: payments.userId > users.userId

Ref: recipe_steps.recipeId > recipes.recipeId
Ref: course_steps.courseId > courses.courseId