'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface) {
        const now = new Date();
        const passwordHash = '$2b$10$CwTycUXWue0Thq9StjUM0uJ8rq2bOMfOeXtfLOcAfeUeawuO/7d4.'; // bcrypt hash for "password"
        const users = [
            {
                userId: 1,
                genderId: 1,
                roleId: 1,
                firstName: 'Alice',
                lastName: 'Nguyen',
                email: 'alice.admin@example.com',
                username: 'alice_admin',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=1',
                bio: 'Admin of the platform',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 2,
                genderId: 2,
                roleId: 2,
                firstName: 'Bao',
                lastName: 'Tran',
                email: 'bao.instructor@example.com',
                username: 'bao_instructor',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=2',
                bio: 'Chef & instructor specializing in Vietnamese cuisine',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 3,
                genderId: 1,
                roleId: 2,
                firstName: 'Carlos',
                lastName: 'Diaz',
                email: 'carlos.instructor@example.com',
                username: 'carlos_instructor',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=3',
                bio: 'Instructor focused on street food classics',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 4,
                genderId: 2,
                roleId: 3,
                firstName: 'Diana',
                lastName: 'Pham',
                email: 'diana.member@example.com',
                username: 'diana_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=4',
                bio: 'Home cook exploring new recipes',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 5,
                genderId: 3,
                roleId: 3,
                firstName: 'Evan',
                lastName: 'Lee',
                email: 'evan.member@example.com',
                username: 'evan_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=5',
                bio: 'Loves comfort food and quick meals',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 6,
                genderId: 1,
                roleId: 3,
                firstName: 'Felix',
                lastName: 'Wong',
                email: 'felix.member@example.com',
                username: 'felix_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=6',
                bio: 'Enjoys quick stir-fry dinners',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 7,
                genderId: 2,
                roleId: 3,
                firstName: 'Grace',
                lastName: 'Lopez',
                email: 'grace.member@example.com',
                username: 'grace_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=7',
                bio: 'Baker in progress, loves pastries',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 8,
                genderId: 1,
                roleId: 2,
                firstName: 'Huy',
                lastName: 'Pham',
                email: 'huy.instructor@example.com',
                username: 'huy_instructor',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=8',
                bio: 'Teaches noodle and soup techniques',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 9,
                genderId: 2,
                roleId: 2,
                firstName: 'Isabella',
                lastName: 'Martinez',
                email: 'isabella.instructor@example.com',
                username: 'isabella_instructor',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=9',
                bio: 'Focus on plant-based comfort food',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 10,
                genderId: 1,
                roleId: 3,
                firstName: 'Jack',
                lastName: 'Taylor',
                email: 'jack.member@example.com',
                username: 'jack_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=10',
                bio: 'Weekend griller and BBQ fan',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 11,
                genderId: 2,
                roleId: 3,
                firstName: 'Kara',
                lastName: 'Singh',
                email: 'kara.member@example.com',
                username: 'kara_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=11',
                bio: 'Exploring Asian fusion cooking',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 12,
                genderId: 1,
                roleId: 3,
                firstName: 'Liam',
                lastName: 'Johnson',
                email: 'liam.member@example.com',
                username: 'liam_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=12',
                bio: 'Meal-prep for busy weekdays',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 13,
                genderId: 2,
                roleId: 2,
                firstName: 'Maya',
                lastName: 'Kim',
                email: 'maya.instructor@example.com',
                username: 'maya_instructor',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=13',
                bio: 'Sauce and marinade specialist',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 14,
                genderId: 1,
                roleId: 3,
                firstName: 'Noah',
                lastName: 'Brown',
                email: 'noah.member@example.com',
                username: 'noah_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=14',
                bio: 'Learning seafood basics',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 15,
                genderId: 2,
                roleId: 3,
                firstName: 'Olivia',
                lastName: 'Garcia',
                email: 'olivia.member@example.com',
                username: 'olivia_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=15',
                bio: 'Enjoys baking and plating desserts',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 16,
                genderId: 1,
                roleId: 2,
                firstName: 'Pedro',
                lastName: 'Silva',
                email: 'pedro.instructor@example.com',
                username: 'pedro_instructor',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=16',
                bio: 'Teaches grilling and roasting',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 17,
                genderId: 2,
                roleId: 3,
                firstName: 'Quinn',
                lastName: 'Reed',
                email: 'quinn.member@example.com',
                username: 'quinn_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=17',
                bio: 'Loves quick salads and bowls',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 18,
                genderId: 1,
                roleId: 3,
                firstName: 'Ravi',
                lastName: 'Patel',
                email: 'ravi.member@example.com',
                username: 'ravi_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=18',
                bio: 'Experimenting with spices',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 19,
                genderId: 2,
                roleId: 3,
                firstName: 'Sara',
                lastName: 'Chen',
                email: 'sara.member@example.com',
                username: 'sara_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=19',
                bio: 'Enjoys noodles and soups',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 20,
                genderId: 1,
                roleId: 3,
                firstName: 'Tom',
                lastName: 'Anderson',
                email: 'tom.member@example.com',
                username: 'tom_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=20',
                bio: 'One-pan meal enthusiast',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 21,
                genderId: 2,
                roleId: 3,
                firstName: 'Uma',
                lastName: 'Verma',
                email: 'uma.member@example.com',
                username: 'uma_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=21',
                bio: 'Loves Thai curries',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 22,
                genderId: 1,
                roleId: 3,
                firstName: 'Victor',
                lastName: 'Ng',
                email: 'victor.member@example.com',
                username: 'victor_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=22',
                bio: 'Weekend brunch maker',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 23,
                genderId: 2,
                roleId: 3,
                firstName: 'Wendy',
                lastName: 'Huang',
                email: 'wendy.member@example.com',
                username: 'wendy_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=23',
                bio: 'Pastry and sweets lover',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 24,
                genderId: 1,
                roleId: 3,
                firstName: 'Xavier',
                lastName: 'Lo',
                email: 'xavier.member@example.com',
                username: 'xavier_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=24',
                bio: 'Trying new grilling rubs',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 25,
                genderId: 2,
                roleId: 3,
                firstName: 'Yara',
                lastName: 'Souza',
                email: 'yara.member@example.com',
                username: 'yara_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=25',
                bio: 'Vegetarian bowls and wraps',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 26,
                genderId: 1,
                roleId: 3,
                firstName: 'Zane',
                lastName: 'Clark',
                email: 'zane.member@example.com',
                username: 'zane_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=26',
                bio: 'Learning pasta from scratch',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 27,
                genderId: 2,
                roleId: 3,
                firstName: 'Amy',
                lastName: 'Foster',
                email: 'amy.member@example.com',
                username: 'amy_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=27',
                bio: 'Sheet-pan dinner fan',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 28,
                genderId: 1,
                roleId: 3,
                firstName: 'Brian',
                lastName: 'Evans',
                email: 'brian.member@example.com',
                username: 'brian_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=28',
                bio: 'Comfort food experiments',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 29,
                genderId: 2,
                roleId: 3,
                firstName: 'Chloe',
                lastName: 'Adams',
                email: 'chloe.member@example.com',
                username: 'chloe_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=29',
                bio: 'Fresh salads and smoothies',
                createdAt: now,
                updatedAt: now
            },
            {
                userId: 30,
                genderId: 1,
                roleId: 3,
                firstName: 'Derek',
                lastName: 'Baker',
                email: 'derek.member@example.com',
                username: 'derek_member',
                password: passwordHash,
                avatarUrl: 'https://i.pravatar.cc/300?img=30',
                bio: 'Exploring global street food',
                createdAt: now,
                updatedAt: now
            }
        ];

        await queryInterface.bulkInsert('users', users, {});
    },

    async down(queryInterface) {
        await queryInterface.bulkDelete('users', null, {});
    }
};

